version: "2"
services:
    nginx:
        image: nginx:1.12.1-alpine
        ports:
            - "80:80"
        volumes_from:
            - php5.6
        volumes:
            - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/nginx/vhost:/etc/nginx/conf.d
    php5.6:
        image: hellomjw/php:5.6_v2.0.1
        volumes:
            - ./wwwroot:/home/wwwroot
            - ./app/php5.6/conf/php.ini:/usr/local/etc/php/php.ini
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test123"
    redis:
        image: redis:4-alpine
        ports:
            - "6379:6379"
        
    memcached:
        image: memcached:1.5-alpine
        ports:
            - "11211:11211"

        
